# Change these first
owner: bajahaw 
repo: web-monitor

sites:
  - name: bajahaw.com
    url: https://www.bajahaw.com
  - name: Portfolio
    url: https://portfolio.bajahaw.com
  - name: URL Shortener
    url: https://url.bajahaw.com/health
  - name: Multi tic tac
    url: https://multi-tic-tac.onrender.com

status-website:
  cname: status.bajahaw.com
  # baseUrl: /web-monitor
  theme: light
  logoUrl: https://backend.bajahaw.com/favicon.png
  name: Upptime
  introTitle: "**bajahaw.com Status**"
  introMessage: Static status page with **real-time** data
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO
