# Change these first
owner: bajahaw 
repo: web-monitor

sites:
  - name: radhi.tech
    url: https://www.radhi.tech
  - name: Portfolio
    url: https://portfolio.radhi.tech
  - name: Backend infrastructure
    url: https://backend.radhi.tech/_
  - name: Multi tic tac
    url: https://multi-tic-tac.onrender.com

status-website:
  cname: status.radhi.tech
  # baseUrl: /web-monitor
  theme: light
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: Upptime
  introTitle: "**radhi.tech Status**"
  introMessage: Static status page with **real-time** data
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO
